export interface SharePointKnowledgeColumnMap {
  fileName: string;
  title: string;
  description: string;
  author: string;
  published: string;
  contentRefreshDate: string;
  url: string;
  status: string;
  views: string;
  likes: string;
  comments: string;
  downloads: string;
  follow: string;
  share: string;
  bookmark: string;
  sensitiveTerms: string;
  reviewerComments: string;
  projectId: string;
  versionFileName: string;
  versionFileType: string;
  documentType: string;
  geography: string;
  client: string;
  diseaseArea: string;
  therapyArea: string;
  bu: string;
  department: string;
  created: string;
  modified: string;
  createdBy: string;
  modifiedBy: string;
  version: string;
}

export const defaultKnowledgeColumnMap: SharePointKnowledgeColumnMap = {
  fileName: 'FileLeafRef',
  title: 'Title',
  description: 'Description',
  author: 'Author0',
  published: 'Published',
  contentRefreshDate: 'ContentRefreshDate',
  url: 'URL',
  status: 'Status',
  views: 'Views',
  likes: 'Likes',
  comments: 'Comments',
  downloads: 'Downloads',
  follow: 'Follow',
  share: 'Share',
  bookmark: 'Bookmark',
  sensitiveTerms: 'SensitiveTerms',
  reviewerComments: 'ReviewerComments',
  projectId: 'ProjectId',
  versionFileName: 'VersionFileName',
  versionFileType: 'VersionFileType',
  documentType: 'Document_x0020_Type',
  geography: 'Geography',
  client: 'Client',
  diseaseArea: 'Disease_x0020_Area',
  therapyArea: 'Therapy_x0020_Area',
  bu: 'BU',
  department: 'Department_x0020__x002f__x0020_Sub_x0020_Department',
  created: 'Created',
  modified: 'Modified',
  createdBy: 'Author',
  modifiedBy: 'Editor',
  version: 'Version'
};
